name: Build OpenCV xcframework

on:
  workflow_dispatch:
  workflow_call:


env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.0.app
  OPENCV_VERSION: "4.11.0"
  TAG_NAME: "xcode_16.2.0"

jobs:
  build:
    runs-on: macos-15
    permissions: 
      contents: write
    steps:
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 3.29.2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: minimum-opencv-xcframework

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Checkout OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          ref: refs/tags/${{ env.OPENCV_VERSION }}
          path: 'opencv'
      
      - name: Build xcframework
        working-directory: opencv
        env:
          IPHONEOS_DEPLOYMENT_TARGET: 12.0
          MACOSX_DEPLOYMENT_TARGET: 10.13
        run: |
          pip3 install pathlib
          python3 platforms/apple/build_xcframework.py \
              `cat $GITHUB_WORKSPACE/minimum-opencv-xcframework/opencv_without.txt` \
              --iphoneos_archs=arm64 \
              --iphonesimulator_archs=arm64 \
              --build_only_specified_archs \
              -o build

      - name: Zip artifact
        working-directory: opencv
        run: zip -ry opencv2.xcframework.zip build/opencv2.xcframework

      - name: Put zip info to Release.txt
        run: |
            echo "\`\`\`json" >> Release.txt
            echo "{" >> Release.txt
            echo "  \"Checksum\": \"$(sha256sum opencv/opencv2.xcframework.zip | cut -d ' ' -f 1)\"," >> Release.txt
            echo "  \"OpenCV\": \"${{ env.OPENCV_VERSION  }}\"," >> Release.txt
            echo "  \"Xcode\": \"$(xcodebuild -version | tr '\n' ' ')\"" >> Release.txt
            echo "}" >> Release.txt
            echo "\`\`\`" >> Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: Release.txt
          files: opencv/opencv2.xcframework.zip
          tag_name: ${{ env.TAG_NAME }}
