name: Build OpenCV xcframework

on:
  workflow_dispatch:
  workflow_call:


env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.0.app

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: 3.29.2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: minimum-opencv-xcframework

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Get version
        id: get_version
        working-directory: minimum-opencv-xcframework
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Checkout OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          ref: refs/tags/${{ steps.get_version.outputs.VERSION }}
          path: 'opencv'
      
      - name: Build xcframework
        working-directory: opencv
        env:
          IPHONEOS_DEPLOYMENT_TARGET: 12.0
          MACOSX_DEPLOYMENT_TARGET: 10.13
        run: |
          pip3 install pathlib
          python3 platforms/apple/build_xcframework.py \
              `cat $GITHUB_WORKSPACE/minimum-opencv-xcframework/opencv_without.txt` \
              --iphoneos_archs=arm64 \
              --iphonesimulator_archs=arm64 \
              --build_only_specified_archs \
              -o build

      - name: Zip artifact
        working-directory: opencv
        run: zip -ry opencv2.xcframework.zip build/opencv2.xcframework

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencv2.xcframework.zip
          path: opencv/opencv2.xcframework.zip
          if-no-files-found: error
