name: Build and release a new version

on:
  push:
    branches: [ "main" ]
    paths: [ ".version" ]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: opencv2.xcframework.zip

      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat .version)
          if git rev-parse -q --verify "refs/tags/${VERSION}" >/dev/null; then
            PATCH=$(git rev-list --count "refs/tags/${VERSION}..HEAD")
            VERSION="${VERSION}+${PATCH}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Put zip info to Release.txt
        run: |
          echo "\`\`\`json" >> Release.txt
          echo "{" >> Release.txt
          echo "  \"DownloadSize\": $(stat --printf=%s opencv2.xcframework.zip)," >> Release.txt
          echo "  \"Checksum\": \"$(sha256sum opencv2.xcframework.zip | cut -d ' ' -f 1)\"," >> Release.txt
          echo "  \"OpenCV\": \"${{ steps.get_version.outputs.VERSION }}\"," >> Release.txt
          echo "  \"Xcode\": \"$(xcodebuild -version)\"" >> Release.txt
          echo "}" >> Release.txt
          echo "\`\`\`" >> Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: Release.txt
          files: opencv2.xcframework.zip
